language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-23.0.3
    # The SDK version used to compile your project
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support

licenses:
    - '.+'

email: false
    
script:
   - ./gradlew build connectedCheck
   
before_install:
    - chmod +x gradlew

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
